# CMake generated Testfile for 
# Source directory: /scratch/globc/page/cyclone_tracking/json-fortran-6.9.0
# Build directory: /scratch/globc/page/cyclone_tracking/json-fortran
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(jf_test_01 "./jf_test_01")
set_tests_properties(jf_test_01 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_02 "./jf_test_02")
set_tests_properties(jf_test_02 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_03 "./jf_test_03")
set_tests_properties(jf_test_03 PROPERTIES  DEPENDS "jf_test_02" WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_04 "./jf_test_04")
set_tests_properties(jf_test_04 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_05 "./jf_test_05")
set_tests_properties(jf_test_05 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_06 "./jf_test_06")
set_tests_properties(jf_test_06 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_07 "./jf_test_07")
set_tests_properties(jf_test_07 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_08 "./jf_test_08")
set_tests_properties(jf_test_08 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_09 "./jf_test_09")
set_tests_properties(jf_test_09 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_10 "./jf_test_10")
set_tests_properties(jf_test_10 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_11 "./jf_test_11")
set_tests_properties(jf_test_11 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_12 "./jf_test_12")
set_tests_properties(jf_test_12 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_13 "./jf_test_13")
set_tests_properties(jf_test_13 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_14 "./jf_test_14")
set_tests_properties(jf_test_14 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_15 "./jf_test_15")
set_tests_properties(jf_test_15 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_16 "./jf_test_16")
set_tests_properties(jf_test_16 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_17 "./jf_test_17")
set_tests_properties(jf_test_17 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_18 "./jf_test_18")
set_tests_properties(jf_test_18 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_19 "./jf_test_19")
set_tests_properties(jf_test_19 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_20 "./jf_test_20")
set_tests_properties(jf_test_20 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_21 "./jf_test_21")
set_tests_properties(jf_test_21 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_22 "./jf_test_22")
set_tests_properties(jf_test_22 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_23 "./jf_test_23")
set_tests_properties(jf_test_23 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_24 "./jf_test_24")
set_tests_properties(jf_test_24 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_25 "./jf_test_25")
set_tests_properties(jf_test_25 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_26 "./jf_test_26")
set_tests_properties(jf_test_26 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_27 "./jf_test_27")
set_tests_properties(jf_test_27 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_28 "./jf_test_28")
set_tests_properties(jf_test_28 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_29 "./jf_test_29")
set_tests_properties(jf_test_29 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_30 "./jf_test_30")
set_tests_properties(jf_test_30 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_31 "./jf_test_31")
set_tests_properties(jf_test_31 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_32 "./jf_test_32")
set_tests_properties(jf_test_32 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_33 "./jf_test_33")
set_tests_properties(jf_test_33 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_34 "./jf_test_34")
set_tests_properties(jf_test_34 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
add_test(jf_test_35 "./jf_test_35")
set_tests_properties(jf_test_35 PROPERTIES  WORKING_DIRECTORY "/scratch/globc/page/cyclone_tracking/json-fortran/bin")
