#!/bin/sh
#

vars_sfc="psl"
vars_500="ua500 va500"
vars_1000="zg1000"
vars_cst="z lsm"

inc="1d"
period="19790101_20161231"
model="ERAI"
latbox="30.,60."
lonbox="330.,30."

outfile="${period}_${model}.nc"

mkdir -p results

# ncks -d time,0,365 -d latitude,${latbox} -d longitude,-30.,30. uas_day_CNRM-CM5_rcp85_r1i1p1_20060101-21001231.nc out.nc
#-rwxr-xr-x 1 page globc 1.6G Sep 22 16:01 psl_1d_19790101_20161231_ERAI.nc*
#-rwxr-xr-x 1 page globc 1.6G Sep 22 16:02 ua500_1d_19790101_20161231_ERAI.nc*
#-rwxr-xr-x 1 page globc 1.6G Sep 22 16:02 va500_1d_19790101_20161231_ERAI.nc*
#-rw-r--r-- 1 page globc 1.6G Sep 25 14:21 zg1000_1d_19790101_20161231_ERAI.nc
#-rwxr-xr-x 1 page globc  60K Sep 22 15:59 z_ERAI.nc*

rm -f results/${outfile}

for i in ${vars_sfc}
do

filename=${i}_${inc}_${period}_${model}.nc

rm -f results/$filename
ncks -O -d time,0,3650 -d latitude,${latbox} -d longitude,${lonbox} ${filename} results/${filename}
if [ ! -s results/${outfile} ]
then
  cp results/${filename} results/${outfile}
else
  ncks -h -A results/${filename} results/${outfile}
fi

done


for i in ${vars_500}
do

filename=${i}_${inc}_${period}_${model}.nc

rm -f results/$filename
ncks -O -d time,0,3650 -d latitude,${latbox} -d longitude,${lonbox} ${filename} results/${filename}
if [ ! -s results/${outfile} ]
then
  cp results/${filename} results/${outfile}
else
  ncks -h -A results/${filename} results/${outfile}
fi

done

for i in ${vars_1000}
do

filename=${i}_${inc}_${period}_${model}.nc

rm -f results/$filename
ncks -O -d time,0,3650 -d latitude,${latbox} -d longitude,${lonbox} ${filename} results/${filename}
if [ ! -s results/${outfile} ]
then
  cp results/${filename} results/${outfile}
else
  ncks -h -A results/${filename} results/${outfile}
fi

done

for i in ${vars_cst}
do

filename=${i}_${model}.nc

rm -f results/$filename
ncks -O -d latitude,${latbox} -d longitude,${lonbox} ${filename} results/${filename}

done
